var i18n = $.extend({}, i18n || {}, {
    xgcalendar: {
        dateformat: {
            "fulldaykey": "ddMMyyyy",
            "fulldayshow": "L d yyyy",
            "fulldayvalue": "d/M/yyyy",
            "Md": "W d/M",
            "Md3": "L d",
            "separator": "/",
            "year_index": 2,
            "month_index": 0,
            "day_index": 1,
            "day": "d",
            "sun": "Dom",
            "mon": "Lun",
            "tue": "Mar",
            "wed": "Mer",
            "thu": "Gio",
            "fri": "Ven",
            "sat": "Sab",
            "jan": "Gen",
            "feb": "Feb",
            "mar": "Mar",
            "apr": "Apr",
            "may": "Mag",
            "jun": "Giu",
            "jul": "Lug",
            "aug": "Ago",
            "sep": "Set",
            "oct": "Ott",
            "nov": "Nov",
            "dec": "Dic"
        },
        "no_implemented": "Non ancora implementato",
        "to_date_view": "Clicca per vedere la data corrente",
        "i_undefined": "Non definito",
        "allday_event": "Evento giornaliero",
        "repeat_event": "Ripeti evento",
        "time": "Tempo",
        "event": "Evento",
        "location": "Luogo",
        "participant": "Partecipante",
        "get_data_exception": "Errore quando recupero i dati",
        "new_event": "Nuovo evento",
        "confirm_delete_event": "Confermi di cancellare l'evento?",
        "confrim_delete_event_or_all": "Vuoi cancellare tutti gli eventi ripetuti o solo questo evento? \r\nClicca [OK] per cancellare solo questo evento, clicca [Cancel] per cancellare tutti gli eventi",
        "data_format_error": "Errore nel formato di data",
        "invalid_title": "Il titolo dell'evento non può essere vuoto o contenere ($<>)",
        "view_no_ready": "La vista non è pronta",
        "example": "per es., riunione alla stanza 107",
        "content": "Cosa",
        "create_event": "Crea evento",
        "update_detail": "Modifica i dettagli",
        "click_to_detail": "Visualizza i dettagli",
        "i_delete": "Cancella",
        "day_plural": "giorni",
        "others": "Altri",
        "item": ""
    }
});
